### ISSUE TITLE
Build error with CMake under ubuntu v18

### ISSUE THREAD

**Issue by HenryXin** [vegesm/first-cc-gcc#2]
cmake version 3.10.2
Hi there, 

It could not be built under my ubuntu server as:

cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release
CMake Error: The source directory "/home/henry/Study/FunFromGithub/avium/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks

**Comment by vegesm** [comment]
the project uses make, not cmake
